from pynput.keyboard import Key, Controller
import time

keyboard = Controller()
keyboard.press(Key.space)
keyboard.release(Key.space)

time.sleep (10)
while(True):
    for char in "911 trevor daniel":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(154)
    for char in "Shakira! 1nonly":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(150)
    for char in "little submarine UIt liefde voor muziek":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(198)
    for char in "Beggin Logic":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(199)
    for char in "The Box Roddy Rich":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(213)
    for char in "All night Icona Pop":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(181)
    for char in "El Chapo Skrillex":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(221)
    for char in "Ballin Logic":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(230)
    for char in "play for the keeps La capone":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(234)
    for char in "love the way you lie Eminem":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(267)
    for char in "Wombo Combo Shotgun WIlly":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(181)
    for char in "Shotgun Willy - Wendy (Lyrics) HD":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(163)
    for char in "30 fukkit":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(161)
    for char in "Treasure Bruno mars":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(192)
    for char in "PTSD juice world":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(233)
    for char in "Tunnel Vision Kodak black":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(272)
    for char in "Goat The kidszn":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(145)
    for char in "Pepperspray Darwin":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(240)
    for char in "Flashbang fukkit":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(240)
    for char in "Stop snitching YG":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(160)
    for char in "Deadz Migos":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(160)
    for char in "Nightcore - We can Do this all Night":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(354)
    for char in "Earth, Wind & Fire - September (Official Video)":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(210)
    for char in "How To Say Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(203)
    for char in "KC & The Sunshine Band - Give It Up":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(240)
    for char in "Nightcore - Rasputin (Remix) (For Mother Russia)":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(274)
    for char in "Initial D - Deja Vu":
        keyboard.press(char)
        keyboard.release(char)
        time.sleep(0.12)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    time.sleep(265)

